#Program to find out the total marks recieved in a subject and its Percentage
choice=input ('NEW!! Now calclate the entire marks of the exam. Warning. No Decimals will work. Please type in Integers. If an error occurs, stop the execution and try again.  Are you interested in this, or do you want subject-by-subject calculation? Please type YES or NO.')
if choice=='YES':
    print ('OK.')
    sciencechoice=int(input('Enter the marks recieved for Science.'))
    socialchoice=int(input('Enter the marks recieved for Social.'))
    mathschoice=int(input('Enter the marks recieved for Maths.'))
    englishchoice=int(input('Enter the marks recieved for English.'))
    hindichoice=int(input('Enter the marks recieved for Hindi.'))
    sanskritchoice=int(input('Enter the marks recieved for Sanskrit.'))
    totalchoice=int(sciencechoice+socialchoice+mathschoice+englishchoice+hindichoice+sanskritchoice)
    howmuchchoice=int(input('Enter the total marks for the exams.'))
    percentagechoice=int((totalchoice/howmuchchoice)*100)
    print ('You total marks in exams is', totalchoice)
    print ('Your mark percentage in exams is', percentagechoice, '%')
elif choice=='yes':
    sciencechoice=int(input('Enter the marks recieved for Science.'))
    socialchoice=int(input('Enter the marks recieved for Social.'))
    mathschoice=int(input('Enter the marks recieved for Maths.'))
    englishchoice=int(input('Enter the marks recieved for English.'))
    hindichoice=int(input('Enter the marks recieved for Hindi.'))
    sanskritchoice=int(input('Enter the marks recieved for Sanskrit.'))
    totalchoice=int(sciencechoice+socialchoice+mathschoice+englishchoice+hindichoice+sanskritchoice)
    howmuchchoice=int(input('Enter the total marks for the exams.'))
    percentagechoice=int((totalchoice/howmuchchoice)*100)
    print ('You total marks in exams is', totalchoice)
    print ('Your mark percentage in exams is', percentagechoice, '%')
elif choice=='Yes':
    sciencechoice=int(input('Enter the marks recieved for Science.'))
    socialchoice=int(input('Enter the marks recieved for Social.'))
    mathschoice=int(input('Enter the marks recieved for Maths.'))
    englishchoice=int(input('Enter the marks recieved for English.'))
    hindichoice=int(input('Enter the marks recieved for Hindi.'))
    sanskritchoice=int(input('Enter the marks recieved for Sanskrit.'))
    totalchoice=int(sciencechoice+socialchoice+mathschoice+englishchoice+hindichoice+sanskritchoice)
    howmuchchoice=int(input('Enter the total marks for the exams.'))
    percentagechoice=int((totalchoice/howmuchchoice)*100)
    print ('You total marks in exams is', totalchoice)
    print ('Your mark percentage in exams is', percentagechoice, '%')    
if choice=='No':
    subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    print ('Warning. Enter a valid subject.')
    subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Science
    if subject=='Science':
        print ('OK.')
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='General Science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='general science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Social Science
    if subject=='Social Science':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='Social':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='social':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='social science':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Maths
    if subject=='Mathematics':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='Maths':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='maths':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='mathematics':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Hindi    
    if subject=='Hindi':
        print ('OK.')
        Hindi=int(input('Enter the marks recieved for Hindi.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalHindi=int(Hindi)
        percentageHindi=int((Hindi/HowMuch)*100)
        print ('You total marks in Hindi is', Hindi)
        print ('Your mark percentage in Hindi is', percentageHindi, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='hindi':
        print ('OK.')
        Hindi=int(input('Enter the marks recieved for Hindi.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalHindi=int(Hindi)
        percentageHindi=int((Hindi/HowMuch)*100)
        print ('You total marks in Hindi is', Hindi)
        print ('Your mark percentage in Hindi is', percentageHindi, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for English   
    if subject=='English':
        print ('OK.')
        English=int(input('Enter the marks recieved for English.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalEnglish=int(English)
        percentageEnglish=int((English/HowMuch)*100)
        print ('You total marks in English is', English)
        print ('Your mark percentage in English is', percentageEnglish, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='english':
        print ('OK.')
        English=int(input('Enter the marks recieved for English.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalEnglish=int(English)
        percentageEnglish=int((English/HowMuch)*100)
        print ('You total marks in English is', English)
        print ('Your mark percentage in English is', percentageEnglish, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Sanskrit   
    if subject=='Sanskrit':
        print ('OK.')
        Sanskrit=int(input('Enter the marks recieved for Sanskrit.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSanskrit=int(Sanskrit)
        percentageSasrkit=int((Sanskrit/HowMuch)*100)
        print ('You total marks in Sanskrit is', Sanskrit)
        print ('Your mark percentage in Sanskrit is', percentageSasrkit, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='sanskrit':
        print ('OK.')
        Sanskrit=int(input('Enter the marks recieved for Sanskrit.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSanskrit=int(Sanskrit)
        percentageSasrkit=int((Sanskrit/HowMuch)*100)
        print ('You total marks in Sanskrit is', Sanskrit)
        print ('Your mark percentage in Sanskrit is', percentageSasrkit, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
if choice=='no':
    subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    print ('Warning. Enter a valid subject.')
    subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Science
    if subject=='Science':
        print ('OK.')
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='General Science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='general science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Social Science
    if subject=='Social Science':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='Social':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='social':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='social science':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Maths
    if subject=='Mathematics':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='Maths':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='maths':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='mathematics':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Hindi    
    if subject=='Hindi':
        print ('OK.')
        Hindi=int(input('Enter the marks recieved for Hindi.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalHindi=int(Hindi)
        percentageHindi=int((Hindi/HowMuch)*100)
        print ('You total marks in Hindi is', Hindi)
        print ('Your mark percentage in Hindi is', percentageHindi, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='hindi':
        print ('OK.')
        Hindi=int(input('Enter the marks recieved for Hindi.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalHindi=int(Hindi)
        percentageHindi=int((Hindi/HowMuch)*100)
        print ('You total marks in Hindi is', Hindi)
        print ('Your mark percentage in Hindi is', percentageHindi, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for English   
    if subject=='English':
        print ('OK.')
        English=int(input('Enter the marks recieved for English.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalEnglish=int(English)
        percentageEnglish=int((English/HowMuch)*100)
        print ('You total marks in English is', English)
        print ('Your mark percentage in English is', percentageEnglish, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='english':
        print ('OK.')
        English=int(input('Enter the marks recieved for English.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalEnglish=int(English)
        percentageEnglish=int((English/HowMuch)*100)
        print ('You total marks in English is', English)
        print ('Your mark percentage in English is', percentageEnglish, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Sanskrit   
    if subject=='Sanskrit':
        print ('OK.')
        Sanskrit=int(input('Enter the marks recieved for Sanskrit.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSanskrit=int(Sanskrit)
        percentageSasrkit=int((Sanskrit/HowMuch)*100)
        print ('You total marks in Sanskrit is', Sanskrit)
        print ('Your mark percentage in Sanskrit is', percentageSasrkit, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='sanskrit':
        print ('OK.')
        Sanskrit=int(input('Enter the marks recieved for Sanskrit.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSanskrit=int(Sanskrit)
        percentageSasrkit=int((Sanskrit/HowMuch)*100)
        print ('You total marks in Sanskrit is', Sanskrit)
        print ('Your mark percentage in Sanskrit is', percentageSasrkit, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
if choice=='NO':
    subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    print ('Warning. Enter a valid subject.')
    subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Science
    if subject=='Science':
        print ('OK.')
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='General Science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='general science':
        Physics=int(input('Enter the marks recieved for Physics.'))
        Chemistry=int(input('Enter the marks recieved for Chemistry.'))
        Biology=int(input('Enter the marks recieved for Biology.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalScience=int(Physics+Chemistry+Biology)
        percentageScience=int((totalScience/HowMuch)*100)
        print ('You total marks in Science is', totalScience)
        print ('Your mark percentage in Science is', percentageScience, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Social Science
    if subject=='Social Science':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='Social':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='social':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='social science':
        print ('OK.')
        Social=int(input('Enter the marks recieved for Social Science.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSocial=int(Social)
        percentageSocial=int((Social/HowMuch)*100)
        print ('You total marks in Social is', Social)
        print ('Your mark percentage in Social is', percentageSocial, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Maths
    if subject=='Mathematics':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='Maths':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='maths':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='mathematics':
        print ('OK.')
        Maths=int(input('Enter the marks recieved for Maths.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalMaths=int(Maths)
        percentageMaths=int((Maths/HowMuch)*100)
        print ('You total marks in Maths is', Maths)
        print ('Your mark percentage in Maths is', percentageMaths, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Hindi    
    if subject=='Hindi':
        print ('OK.')
        Hindi=int(input('Enter the marks recieved for Hindi.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalHindi=int(Hindi)
        percentageHindi=int((Hindi/HowMuch)*100)
        print ('You total marks in Hindi is', Hindi)
        print ('Your mark percentage in Hindi is', percentageHindi, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='hindi':
        print ('OK.')
        Hindi=int(input('Enter the marks recieved for Hindi.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalHindi=int(Hindi)
        percentageHindi=int((Hindi/HowMuch)*100)
        print ('You total marks in Hindi is', Hindi)
        print ('Your mark percentage in Hindi is', percentageHindi, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for English   
    if subject=='English':
        print ('OK.')
        English=int(input('Enter the marks recieved for English.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalEnglish=int(English)
        percentageEnglish=int((English/HowMuch)*100)
        print ('You total marks in English is', English)
        print ('Your mark percentage in English is', percentageEnglish, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='english':
        print ('OK.')
        English=int(input('Enter the marks recieved for English.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalEnglish=int(English)
        percentageEnglish=int((English/HowMuch)*100)
        print ('You total marks in English is', English)
        print ('Your mark percentage in English is', percentageEnglish, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    #This section is for Sanskrit   
    if subject=='Sanskrit':
        print ('OK.')
        Sanskrit=int(input('Enter the marks recieved for Sanskrit.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSanskrit=int(Sanskrit)
        percentageSasrkit=int((Sanskrit/HowMuch)*100)
        print ('You total marks in Sanskrit is', Sanskrit)
        print ('Your mark percentage in Sanskrit is', percentageSasrkit, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')
    elif subject=='sanskrit':
        print ('OK.')
        Sanskrit=int(input('Enter the marks recieved for Sanskrit.'))
        HowMuch=int(input('How much was the Total Marks'))
        totalSanskrit=int(Sanskrit)
        percentageSasrkit=int((Sanskrit/HowMuch)*100)
        print ('You total marks in Sanskrit is', Sanskrit)
        print ('Your mark percentage in Sanskrit is', percentageSasrkit, '%')
        subject=input('Enter the subject you want to calculate the total marks and its Percentage')